package com.tyut.epms.dao;

import com.tyut.epms.bean.Attendance;
import com.tyut.epms.bean.AttendanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AttendanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    long countByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int deleteByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int insert(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int insertSelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    List<Attendance> selectByExample(AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    Attendance selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByExample(@Param("record") Attendance record, @Param("example") AttendanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByPrimaryKeySelective(Attendance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByPrimaryKey(Attendance record);
}