package com.tyut.epms.dao;

import com.tyut.epms.bean.Leave;
import com.tyut.epms.bean.LeaveExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LeaveMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    long countByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int deleteByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int insert(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int insertSelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    List<Leave> selectByExample(LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    Leave selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int updateByExampleSelective(@Param("record") Leave record, @Param("example") LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int updateByExample(@Param("record") Leave record, @Param("example") LeaveExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int updateByPrimaryKeySelective(Leave record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table leave1
     *
     * @mbg.generated Thu Mar 26 14:14:18 CST 2020
     */
    int updateByPrimaryKey(Leave record);
}