package com.tyut.epms.dao;

import com.tyut.epms.bean.Subatt;
import com.tyut.epms.bean.SubattExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SubattMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    long countByExample(SubattExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int deleteByExample(SubattExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int insert(Subatt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int insertSelective(Subatt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    List<Subatt> selectByExample(SubattExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    Subatt selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") Subatt record, @Param("example") SubattExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByExample(@Param("record") Subatt record, @Param("example") SubattExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByPrimaryKeySelective(Subatt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    int updateByPrimaryKey(Subatt record);
}