package com.tyut.epms.bean;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.id
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.emp_id
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private Long empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.emp_name
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.att_date
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date attDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.am_date1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date amDate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.am_state1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private String amState1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.am_date2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date amDate2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.am_state2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private String amState2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.pm_date1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date pmDate1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.pm_state1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private String pmState1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.pm_date2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date pmDate2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.pm_state2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private String pmState2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column attendance.att_state
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    private Integer attState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.id
     *
     * @return the value of attendance.id
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.id
     *
     * @param id the value for attendance.id
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.emp_id
     *
     * @return the value of attendance.emp_id
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.emp_id
     *
     * @param empId the value for attendance.emp_id
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.emp_name
     *
     * @return the value of attendance.emp_name
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.emp_name
     *
     * @param empName the value for attendance.emp_name
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.att_date
     *
     * @return the value of attendance.att_date
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Date getAttDate() {
        return attDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.att_date
     *
     * @param attDate the value for attendance.att_date
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setAttDate(Date attDate) {
        this.attDate = attDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.am_date1
     *
     * @return the value of attendance.am_date1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Date getAmDate1() {
        return amDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.am_date1
     *
     * @param amDate1 the value for attendance.am_date1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setAmDate1(Date amDate1) {
        this.amDate1 = amDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.am_state1
     *
     * @return the value of attendance.am_state1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getAmState1() {
        return amState1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.am_state1
     *
     * @param amState1 the value for attendance.am_state1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setAmState1(String amState1) {
        this.amState1 = amState1 == null ? null : amState1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.am_date2
     *
     * @return the value of attendance.am_date2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Date getAmDate2() {
        return amDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.am_date2
     *
     * @param amDate2 the value for attendance.am_date2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setAmDate2(Date amDate2) {
        this.amDate2 = amDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.am_state2
     *
     * @return the value of attendance.am_state2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getAmState2() {
        return amState2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.am_state2
     *
     * @param amState2 the value for attendance.am_state2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setAmState2(String amState2) {
        this.amState2 = amState2 == null ? null : amState2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.pm_date1
     *
     * @return the value of attendance.pm_date1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Date getPmDate1() {
        return pmDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.pm_date1
     *
     * @param pmDate1 the value for attendance.pm_date1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setPmDate1(Date pmDate1) {
        this.pmDate1 = pmDate1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.pm_state1
     *
     * @return the value of attendance.pm_state1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getPmState1() {
        return pmState1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.pm_state1
     *
     * @param pmState1 the value for attendance.pm_state1
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setPmState1(String pmState1) {
        this.pmState1 = pmState1 == null ? null : pmState1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.pm_date2
     *
     * @return the value of attendance.pm_date2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Date getPmDate2() {
        return pmDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.pm_date2
     *
     * @param pmDate2 the value for attendance.pm_date2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setPmDate2(Date pmDate2) {
        this.pmDate2 = pmDate2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.pm_state2
     *
     * @return the value of attendance.pm_state2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getPmState2() {
        return pmState2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.pm_state2
     *
     * @param pmState2 the value for attendance.pm_state2
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setPmState2(String pmState2) {
        this.pmState2 = pmState2 == null ? null : pmState2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column attendance.att_state
     *
     * @return the value of attendance.att_state
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Integer getAttState() {
        return attState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column attendance.att_state
     *
     * @param attState the value for attendance.att_state
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setAttState(Integer attState) {
        this.attState = attState;
    }

	@Override
	public String toString() {
		return "Attendance [id=" + id + ", empId=" + empId + ", empName=" + empName + ", attDate=" + attDate
				+ ", amDate1=" + amDate1 + ", amState1=" + amState1 + ", amDate2=" + amDate2 + ", amState2=" + amState2
				+ ", pmDate1=" + pmDate1 + ", pmState1=" + pmState1 + ", pmDate2=" + pmDate2 + ", pmState2=" + pmState2
				+ ", attState=" + attState + "]";
	}
    
}