package com.tyut.epms.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class AttendanceExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public AttendanceExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("emp_id is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdEqualTo(Long value) {
            addCriterion("emp_id =", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotEqualTo(Long value) {
            addCriterion("emp_id <>", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThan(Long value) {
            addCriterion("emp_id >", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("emp_id >=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThan(Long value) {
            addCriterion("emp_id <", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("emp_id <=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdIn(List<Long> values) {
            addCriterion("emp_id in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotIn(List<Long> values) {
            addCriterion("emp_id not in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdBetween(Long value1, Long value2) {
            addCriterion("emp_id between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("emp_id not between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("emp_name is null");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("emp_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("emp_name =", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("emp_name <>", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("emp_name >", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_name >=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("emp_name <", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("emp_name <=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("emp_name like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("emp_name not like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameIn(List<String> values) {
            addCriterion("emp_name in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotIn(List<String> values) {
            addCriterion("emp_name not in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("emp_name between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("emp_name not between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andAttDateIsNull() {
            addCriterion("att_date is null");
            return (Criteria) this;
        }

        public Criteria andAttDateIsNotNull() {
            addCriterion("att_date is not null");
            return (Criteria) this;
        }

        public Criteria andAttDateEqualTo(Date value) {
            addCriterionForJDBCDate("att_date =", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("att_date <>", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateGreaterThan(Date value) {
            addCriterionForJDBCDate("att_date >", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("att_date >=", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateLessThan(Date value) {
            addCriterionForJDBCDate("att_date <", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("att_date <=", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateIn(List<Date> values) {
            addCriterionForJDBCDate("att_date in", values, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("att_date not in", values, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("att_date between", value1, value2, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("att_date not between", value1, value2, "attDate");
            return (Criteria) this;
        }

        public Criteria andAmDate1IsNull() {
            addCriterion("am_date1 is null");
            return (Criteria) this;
        }

        public Criteria andAmDate1IsNotNull() {
            addCriterion("am_date1 is not null");
            return (Criteria) this;
        }

        public Criteria andAmDate1EqualTo(Date value) {
            addCriterion("am_date1 =", value, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1NotEqualTo(Date value) {
            addCriterion("am_date1 <>", value, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1GreaterThan(Date value) {
            addCriterion("am_date1 >", value, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1GreaterThanOrEqualTo(Date value) {
            addCriterion("am_date1 >=", value, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1LessThan(Date value) {
            addCriterion("am_date1 <", value, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1LessThanOrEqualTo(Date value) {
            addCriterion("am_date1 <=", value, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1In(List<Date> values) {
            addCriterion("am_date1 in", values, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1NotIn(List<Date> values) {
            addCriterion("am_date1 not in", values, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1Between(Date value1, Date value2) {
            addCriterion("am_date1 between", value1, value2, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmDate1NotBetween(Date value1, Date value2) {
            addCriterion("am_date1 not between", value1, value2, "amDate1");
            return (Criteria) this;
        }

        public Criteria andAmState1IsNull() {
            addCriterion("am_state1 is null");
            return (Criteria) this;
        }

        public Criteria andAmState1IsNotNull() {
            addCriterion("am_state1 is not null");
            return (Criteria) this;
        }

        public Criteria andAmState1EqualTo(String value) {
            addCriterion("am_state1 =", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1NotEqualTo(String value) {
            addCriterion("am_state1 <>", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1GreaterThan(String value) {
            addCriterion("am_state1 >", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1GreaterThanOrEqualTo(String value) {
            addCriterion("am_state1 >=", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1LessThan(String value) {
            addCriterion("am_state1 <", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1LessThanOrEqualTo(String value) {
            addCriterion("am_state1 <=", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1Like(String value) {
            addCriterion("am_state1 like", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1NotLike(String value) {
            addCriterion("am_state1 not like", value, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1In(List<String> values) {
            addCriterion("am_state1 in", values, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1NotIn(List<String> values) {
            addCriterion("am_state1 not in", values, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1Between(String value1, String value2) {
            addCriterion("am_state1 between", value1, value2, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmState1NotBetween(String value1, String value2) {
            addCriterion("am_state1 not between", value1, value2, "amState1");
            return (Criteria) this;
        }

        public Criteria andAmDate2IsNull() {
            addCriterion("am_date2 is null");
            return (Criteria) this;
        }

        public Criteria andAmDate2IsNotNull() {
            addCriterion("am_date2 is not null");
            return (Criteria) this;
        }

        public Criteria andAmDate2EqualTo(Date value) {
            addCriterion("am_date2 =", value, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2NotEqualTo(Date value) {
            addCriterion("am_date2 <>", value, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2GreaterThan(Date value) {
            addCriterion("am_date2 >", value, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2GreaterThanOrEqualTo(Date value) {
            addCriterion("am_date2 >=", value, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2LessThan(Date value) {
            addCriterion("am_date2 <", value, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2LessThanOrEqualTo(Date value) {
            addCriterion("am_date2 <=", value, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2In(List<Date> values) {
            addCriterion("am_date2 in", values, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2NotIn(List<Date> values) {
            addCriterion("am_date2 not in", values, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2Between(Date value1, Date value2) {
            addCriterion("am_date2 between", value1, value2, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmDate2NotBetween(Date value1, Date value2) {
            addCriterion("am_date2 not between", value1, value2, "amDate2");
            return (Criteria) this;
        }

        public Criteria andAmState2IsNull() {
            addCriterion("am_state2 is null");
            return (Criteria) this;
        }

        public Criteria andAmState2IsNotNull() {
            addCriterion("am_state2 is not null");
            return (Criteria) this;
        }

        public Criteria andAmState2EqualTo(String value) {
            addCriterion("am_state2 =", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2NotEqualTo(String value) {
            addCriterion("am_state2 <>", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2GreaterThan(String value) {
            addCriterion("am_state2 >", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2GreaterThanOrEqualTo(String value) {
            addCriterion("am_state2 >=", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2LessThan(String value) {
            addCriterion("am_state2 <", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2LessThanOrEqualTo(String value) {
            addCriterion("am_state2 <=", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2Like(String value) {
            addCriterion("am_state2 like", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2NotLike(String value) {
            addCriterion("am_state2 not like", value, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2In(List<String> values) {
            addCriterion("am_state2 in", values, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2NotIn(List<String> values) {
            addCriterion("am_state2 not in", values, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2Between(String value1, String value2) {
            addCriterion("am_state2 between", value1, value2, "amState2");
            return (Criteria) this;
        }

        public Criteria andAmState2NotBetween(String value1, String value2) {
            addCriterion("am_state2 not between", value1, value2, "amState2");
            return (Criteria) this;
        }

        public Criteria andPmDate1IsNull() {
            addCriterion("pm_date1 is null");
            return (Criteria) this;
        }

        public Criteria andPmDate1IsNotNull() {
            addCriterion("pm_date1 is not null");
            return (Criteria) this;
        }

        public Criteria andPmDate1EqualTo(Date value) {
            addCriterion("pm_date1 =", value, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1NotEqualTo(Date value) {
            addCriterion("pm_date1 <>", value, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1GreaterThan(Date value) {
            addCriterion("pm_date1 >", value, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1GreaterThanOrEqualTo(Date value) {
            addCriterion("pm_date1 >=", value, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1LessThan(Date value) {
            addCriterion("pm_date1 <", value, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1LessThanOrEqualTo(Date value) {
            addCriterion("pm_date1 <=", value, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1In(List<Date> values) {
            addCriterion("pm_date1 in", values, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1NotIn(List<Date> values) {
            addCriterion("pm_date1 not in", values, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1Between(Date value1, Date value2) {
            addCriterion("pm_date1 between", value1, value2, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmDate1NotBetween(Date value1, Date value2) {
            addCriterion("pm_date1 not between", value1, value2, "pmDate1");
            return (Criteria) this;
        }

        public Criteria andPmState1IsNull() {
            addCriterion("pm_state1 is null");
            return (Criteria) this;
        }

        public Criteria andPmState1IsNotNull() {
            addCriterion("pm_state1 is not null");
            return (Criteria) this;
        }

        public Criteria andPmState1EqualTo(String value) {
            addCriterion("pm_state1 =", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1NotEqualTo(String value) {
            addCriterion("pm_state1 <>", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1GreaterThan(String value) {
            addCriterion("pm_state1 >", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1GreaterThanOrEqualTo(String value) {
            addCriterion("pm_state1 >=", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1LessThan(String value) {
            addCriterion("pm_state1 <", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1LessThanOrEqualTo(String value) {
            addCriterion("pm_state1 <=", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1Like(String value) {
            addCriterion("pm_state1 like", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1NotLike(String value) {
            addCriterion("pm_state1 not like", value, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1In(List<String> values) {
            addCriterion("pm_state1 in", values, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1NotIn(List<String> values) {
            addCriterion("pm_state1 not in", values, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1Between(String value1, String value2) {
            addCriterion("pm_state1 between", value1, value2, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmState1NotBetween(String value1, String value2) {
            addCriterion("pm_state1 not between", value1, value2, "pmState1");
            return (Criteria) this;
        }

        public Criteria andPmDate2IsNull() {
            addCriterion("pm_date2 is null");
            return (Criteria) this;
        }

        public Criteria andPmDate2IsNotNull() {
            addCriterion("pm_date2 is not null");
            return (Criteria) this;
        }

        public Criteria andPmDate2EqualTo(Date value) {
            addCriterion("pm_date2 =", value, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2NotEqualTo(Date value) {
            addCriterion("pm_date2 <>", value, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2GreaterThan(Date value) {
            addCriterion("pm_date2 >", value, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2GreaterThanOrEqualTo(Date value) {
            addCriterion("pm_date2 >=", value, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2LessThan(Date value) {
            addCriterion("pm_date2 <", value, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2LessThanOrEqualTo(Date value) {
            addCriterion("pm_date2 <=", value, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2In(List<Date> values) {
            addCriterion("pm_date2 in", values, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2NotIn(List<Date> values) {
            addCriterion("pm_date2 not in", values, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2Between(Date value1, Date value2) {
            addCriterion("pm_date2 between", value1, value2, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmDate2NotBetween(Date value1, Date value2) {
            addCriterion("pm_date2 not between", value1, value2, "pmDate2");
            return (Criteria) this;
        }

        public Criteria andPmState2IsNull() {
            addCriterion("pm_state2 is null");
            return (Criteria) this;
        }

        public Criteria andPmState2IsNotNull() {
            addCriterion("pm_state2 is not null");
            return (Criteria) this;
        }

        public Criteria andPmState2EqualTo(String value) {
            addCriterion("pm_state2 =", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2NotEqualTo(String value) {
            addCriterion("pm_state2 <>", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2GreaterThan(String value) {
            addCriterion("pm_state2 >", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2GreaterThanOrEqualTo(String value) {
            addCriterion("pm_state2 >=", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2LessThan(String value) {
            addCriterion("pm_state2 <", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2LessThanOrEqualTo(String value) {
            addCriterion("pm_state2 <=", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2Like(String value) {
            addCriterion("pm_state2 like", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2NotLike(String value) {
            addCriterion("pm_state2 not like", value, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2In(List<String> values) {
            addCriterion("pm_state2 in", values, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2NotIn(List<String> values) {
            addCriterion("pm_state2 not in", values, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2Between(String value1, String value2) {
            addCriterion("pm_state2 between", value1, value2, "pmState2");
            return (Criteria) this;
        }

        public Criteria andPmState2NotBetween(String value1, String value2) {
            addCriterion("pm_state2 not between", value1, value2, "pmState2");
            return (Criteria) this;
        }

        public Criteria andAttStateIsNull() {
            addCriterion("att_state is null");
            return (Criteria) this;
        }

        public Criteria andAttStateIsNotNull() {
            addCriterion("att_state is not null");
            return (Criteria) this;
        }

        public Criteria andAttStateEqualTo(Integer value) {
            addCriterion("att_state =", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotEqualTo(Integer value) {
            addCriterion("att_state <>", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateGreaterThan(Integer value) {
            addCriterion("att_state >", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateGreaterThanOrEqualTo(Integer value) {
            addCriterion("att_state >=", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateLessThan(Integer value) {
            addCriterion("att_state <", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateLessThanOrEqualTo(Integer value) {
            addCriterion("att_state <=", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateIn(List<Integer> values) {
            addCriterion("att_state in", values, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotIn(List<Integer> values) {
            addCriterion("att_state not in", values, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateBetween(Integer value1, Integer value2) {
            addCriterion("att_state between", value1, value2, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotBetween(Integer value1, Integer value2) {
            addCriterion("att_state not between", value1, value2, "attState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 27 10:17:42 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table attendance
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}