package com.tyut.epms.bean;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String empName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.gender
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.birthday
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dep_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.dep_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String depName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.role_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.role_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.tel
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.email
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.info
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column employee.emp_state
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Integer empState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.id
     *
     * @return the value of employee.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.id
     *
     * @param id the value for employee.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_name
     *
     * @return the value of employee.emp_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getEmpName() {
        return empName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_name
     *
     * @param empName the value for employee.emp_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setEmpName(String empName) {
        this.empName = empName == null ? null : empName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.gender
     *
     * @return the value of employee.gender
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.gender
     *
     * @param gender the value for employee.gender
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender == null ? null : gender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.birthday
     *
     * @return the value of employee.birthday
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.birthday
     *
     * @param birthday the value for employee.birthday
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dep_id
     *
     * @return the value of employee.dep_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dep_id
     *
     * @param depId the value for employee.dep_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.dep_name
     *
     * @return the value of employee.dep_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.dep_name
     *
     * @param depName the value for employee.dep_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.role_id
     *
     * @return the value of employee.role_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.role_id
     *
     * @param roleId the value for employee.role_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.role_name
     *
     * @return the value of employee.role_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.role_name
     *
     * @param roleName the value for employee.role_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.tel
     *
     * @return the value of employee.tel
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.tel
     *
     * @param tel the value for employee.tel
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.email
     *
     * @return the value of employee.email
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.email
     *
     * @param email the value for employee.email
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.info
     *
     * @return the value of employee.info
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.info
     *
     * @param info the value for employee.info
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setInfo(String info) {
        this.info = info == null ? null : info.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column employee.emp_state
     *
     * @return the value of employee.emp_state
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Integer getEmpState() {
        return empState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column employee.emp_state
     *
     * @param empState the value for employee.emp_state
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setEmpState(Integer empState) {
        this.empState = empState;
    }
}