package com.tyut.epms.bean;

public class Login {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.login_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String loginName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.login_password
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String loginPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column login.emp_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long empId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.id
     *
     * @return the value of login.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.id
     *
     * @param id the value for login.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.login_name
     *
     * @return the value of login.login_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.login_name
     *
     * @param loginName the value for login.login_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName == null ? null : loginName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.login_password
     *
     * @return the value of login.login_password
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getLoginPassword() {
        return loginPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.login_password
     *
     * @param loginPassword the value for login.login_password
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setLoginPassword(String loginPassword) {
        this.loginPassword = loginPassword == null ? null : loginPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column login.emp_id
     *
     * @return the value of login.emp_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column login.emp_id
     *
     * @param empId the value for login.emp_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setEmpId(Long empId) {
        this.empId = empId;
    }
}