package com.tyut.epms.bean;

public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.dep_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private Long depId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.dep_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    private String depName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.dep_id
     *
     * @return the value of role.dep_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public Long getDepId() {
        return depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.dep_id
     *
     * @param depId the value for role.dep_id
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setDepId(Long depId) {
        this.depId = depId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.dep_name
     *
     * @return the value of role.dep_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public String getDepName() {
        return depName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.dep_name
     *
     * @param depName the value for role.dep_name
     *
     * @mbg.generated Thu Mar 26 13:35:56 CST 2020
     */
    public void setDepName(String depName) {
        this.depName = depName == null ? null : depName.trim();
    }
}