package com.tyut.epms.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SubattExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public SubattExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNull() {
            addCriterion("emp_id is null");
            return (Criteria) this;
        }

        public Criteria andEmpIdIsNotNull() {
            addCriterion("emp_id is not null");
            return (Criteria) this;
        }

        public Criteria andEmpIdEqualTo(Long value) {
            addCriterion("emp_id =", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotEqualTo(Long value) {
            addCriterion("emp_id <>", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThan(Long value) {
            addCriterion("emp_id >", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdGreaterThanOrEqualTo(Long value) {
            addCriterion("emp_id >=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThan(Long value) {
            addCriterion("emp_id <", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdLessThanOrEqualTo(Long value) {
            addCriterion("emp_id <=", value, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdIn(List<Long> values) {
            addCriterion("emp_id in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotIn(List<Long> values) {
            addCriterion("emp_id not in", values, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdBetween(Long value1, Long value2) {
            addCriterion("emp_id between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpIdNotBetween(Long value1, Long value2) {
            addCriterion("emp_id not between", value1, value2, "empId");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNull() {
            addCriterion("emp_name is null");
            return (Criteria) this;
        }

        public Criteria andEmpNameIsNotNull() {
            addCriterion("emp_name is not null");
            return (Criteria) this;
        }

        public Criteria andEmpNameEqualTo(String value) {
            addCriterion("emp_name =", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotEqualTo(String value) {
            addCriterion("emp_name <>", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThan(String value) {
            addCriterion("emp_name >", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameGreaterThanOrEqualTo(String value) {
            addCriterion("emp_name >=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThan(String value) {
            addCriterion("emp_name <", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLessThanOrEqualTo(String value) {
            addCriterion("emp_name <=", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameLike(String value) {
            addCriterion("emp_name like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotLike(String value) {
            addCriterion("emp_name not like", value, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameIn(List<String> values) {
            addCriterion("emp_name in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotIn(List<String> values) {
            addCriterion("emp_name not in", values, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameBetween(String value1, String value2) {
            addCriterion("emp_name between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andEmpNameNotBetween(String value1, String value2) {
            addCriterion("emp_name not between", value1, value2, "empName");
            return (Criteria) this;
        }

        public Criteria andAttDateIsNull() {
            addCriterion("att_date is null");
            return (Criteria) this;
        }

        public Criteria andAttDateIsNotNull() {
            addCriterion("att_date is not null");
            return (Criteria) this;
        }

        public Criteria andAttDateEqualTo(Date value) {
            addCriterion("att_date =", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotEqualTo(Date value) {
            addCriterion("att_date <>", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateGreaterThan(Date value) {
            addCriterion("att_date >", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateGreaterThanOrEqualTo(Date value) {
            addCriterion("att_date >=", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateLessThan(Date value) {
            addCriterion("att_date <", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateLessThanOrEqualTo(Date value) {
            addCriterion("att_date <=", value, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateIn(List<Date> values) {
            addCriterion("att_date in", values, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotIn(List<Date> values) {
            addCriterion("att_date not in", values, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateBetween(Date value1, Date value2) {
            addCriterion("att_date between", value1, value2, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttDateNotBetween(Date value1, Date value2) {
            addCriterion("att_date not between", value1, value2, "attDate");
            return (Criteria) this;
        }

        public Criteria andAttStateIsNull() {
            addCriterion("att_state is null");
            return (Criteria) this;
        }

        public Criteria andAttStateIsNotNull() {
            addCriterion("att_state is not null");
            return (Criteria) this;
        }

        public Criteria andAttStateEqualTo(String value) {
            addCriterion("att_state =", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotEqualTo(String value) {
            addCriterion("att_state <>", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateGreaterThan(String value) {
            addCriterion("att_state >", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateGreaterThanOrEqualTo(String value) {
            addCriterion("att_state >=", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateLessThan(String value) {
            addCriterion("att_state <", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateLessThanOrEqualTo(String value) {
            addCriterion("att_state <=", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateLike(String value) {
            addCriterion("att_state like", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotLike(String value) {
            addCriterion("att_state not like", value, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateIn(List<String> values) {
            addCriterion("att_state in", values, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotIn(List<String> values) {
            addCriterion("att_state not in", values, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateBetween(String value1, String value2) {
            addCriterion("att_state between", value1, value2, "attState");
            return (Criteria) this;
        }

        public Criteria andAttStateNotBetween(String value1, String value2) {
            addCriterion("att_state not between", value1, value2, "attState");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subatt
     *
     * @mbg.generated do_not_delete_during_merge Fri Mar 27 10:17:42 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table subatt
     *
     * @mbg.generated Fri Mar 27 10:17:42 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}